version: '3.5'

services:
  selenium_chrome:
    container_name: dev_selenium_chrome
    build:
      context: ../..
      dockerfile: docker/selenium_chrome/Dockerfile
    ports:
    - 4444:4444
    shm_size: '8gb'

  crawler-scraper:
    container_name: crawler-scrapper
    environment:
      - DATA_LAKE=/data/
    restart: on-failure

    build:
      context: ../..
      dockerfile: docker/crawler-scrapper/Dockerfile
    volumes:
      - ../../DataLakeProd:/data

    shm_size: '8gb'
    command: bash -c "python3 -u /collector/main.py "