version: '3.5'

services:
  selenium_chrome:
    container_name: dev_selenium_chrome
    build:
      context: ../..
      dockerfile: docker/selenium_chrome/Dockerfile
    ports:
    - 4444:4444
    shm_size: '8gb'